name: Check hosts

on:
  push:
    branches: ["master"]
    paths: ["scripts/auth_hosts/**", ".github/workflows/check_hosts.yml"]
  pull_request:
    paths: ["scripts/auth_hosts/**", ".github/workflows/check_hosts.yml"]
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 6"

jobs:
  check_hosts:
    name: Check for auth hosts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Playwright
        uses: docker/build-push-action@v3
        with:
          context: ./scripts/auth_hosts
          push: false
          tags: auth_hosts:latest
          cache-from: type=gha
          cache-to: type=gha,mode=min
          load: true

      - name: Run checker
        run: |
          docker run auth_hosts:latest > /tmp/report.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: /tmp/report.json
